npm install jsdom --save
npm install express --save
npm install sequelize --save
npm install sqlite3 --save
npm install jquery --save
npm install universal-analytics --save
npm install follow-redirects --save
npm install node-uuid --save
npm install cookies --save
npm install http-post --save
npm install querystring --save
npm install iconv-lite --save
npm install request-promise --save
npm install form-data --save
npm install node-opencc --save